graph TD
  ACAd --> ORBvl
  ACAd --> RSPagl
  ACAd --> SSp-bfd
  ACAd --> VISp
  AId --> AIp
  AIv --> ORBvl
  AUDd --> AUDpo
  AUDd --> AUDv
  AUDd --> SSp-bfd
  AUDd --> SSp-tr
  AUDd --> SSs
  AUDd --> TEa
  AUDd --> VISa
  AUDp --> AUDd
  AUDp --> AUDpo
  AUDp --> VISp
  AUDv --> TEa
  GU --> AId
  ILA --> ACAd
  ILA --> MOs
  MOp --> SSp-ul
  MOp --> SSs
  MOs --> SSp-m
  ORBl --> AId
  ORBl --> FRP
  ORBm --> ACAd
  ORBm --> AIv
  PERI --> AIp
  PERI --> ECT
  PL --> ORBm
  RSPagl --> RSPd
  RSPd --> VISp
  RSPv --> ACAd
  RSPv --> ACAv
  RSPv --> VISa
  SSp-n --> SSs
  SSp-tr --> SSp-ll
  SSp-ul --> SSs
  SSs --> MOs
  TEa --> VISp
  TEa --> VISpor
  VISC --> AId
  VISC --> AIp
  VISC --> MOp
  VISC --> MOs
  VISal --> ACAd
  VISal --> ORBvl
  VISal --> SSs
  VISam --> ORBvl
  VISam --> SSp-bfd
  VISam --> SSp-tr
  VISam --> VISal
  VISam --> VISl
  VISpl --> VISl
  VISpl --> VISpm
  VISpm --> VISam
  VISrl --> ACAd
  VISrl --> RSPagl
  VISrl --> VISam
  VISrl --> VISpm
  ACAd ==> ACAv
ACAd ==> MOs
ACAd ==> PL
ACAd ==> RSPd
ACAd ==> RSPv
AId ==> MOp
AUDd ==> AUDp
AUDp ==> TEa
FRP ==> AId
FRP ==> MOp
FRP ==> MOs
ILA ==> ACAv
ILA ==> PL
ORBl ==> MOs
ORBm ==> PL
ORBvl ==> ORBl
RSPagl ==> VISp
RSPv ==> MOs
SSp-bfd ==> MOs
SSp-bfd ==> SSs
SSp-m ==> MOp
SSp-m ==> MOs
SSp-n ==> MOp
SSp-n ==> MOs
SSp-ul ==> MOp
SSs ==> MOp
SSs ==> SSp-m
VISC ==> SSs
VISal ==> AUDd
VISal ==> AUDp
VISal ==> AUDpo
VISal ==> AUDv
VISal ==> MOs
VISal ==> RSPagl
VISal ==> RSPd
VISal ==> SSp-bfd
VISal ==> TEa
VISal ==> VISa
VISal ==> VISam
VISal ==> VISl
VISal ==> VISli
VISal ==> VISp
VISal ==> VISpm
VISal ==> VISpor
VISam ==> ACAd
VISam ==> MOs
VISam ==> RSPagl
VISam ==> RSPd
VISam ==> RSPv
VISam ==> VISa
VISam ==> VISp
VISam ==> VISpm
VISl ==> VISp
VISpl ==> RSPagl
VISpl ==> RSPd
VISpl ==> TEa
VISpl ==> VISp
VISpl ==> VISpor
VISpm ==> RSPagl
VISpm ==> RSPd
VISpm ==> VISp
VISrl ==> RSPd
VISrl ==> VISa
VISrl ==> VISp
  end
